---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-java
  description: Buildkite Pipeline for elasticsearch-java
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-java

spec:
  type: buildkite-pipeline
  owner: group:devtools-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: Elasticsearch Java Client
      name: elasticsearch-java
    spec:
      repository: elastic/elasticsearch-java
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        devtools-team: {}
        everyone:
          access_level: READ_ONLY
