/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package co.elastic.clients.elasticsearch.inference;

import co.elastic.clients.json.JsonpDeserializable;
import co.elastic.clients.json.JsonpDeserializer;
import co.elastic.clients.json.JsonpMapper;
import co.elastic.clients.json.JsonpSerializable;
import co.elastic.clients.json.JsonpUtils;
import co.elastic.clients.json.ObjectBuilderDeserializer;
import co.elastic.clients.json.ObjectDeserializer;
import co.elastic.clients.util.ApiTypeHelper;
import co.elastic.clients.util.ObjectBuilder;
import co.elastic.clients.util.WithJsonObjectBuilderBase;
import jakarta.json.stream.JsonGenerator;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.function.Function;
import javax.annotation.Nullable;

//----------------------------------------------------------------
//       THIS CODE IS GENERATED. MANUAL EDITS WILL BE LOST.
//----------------------------------------------------------------
//
// This code is generated from the Elasticsearch API specification
// at https://github.com/elastic/elasticsearch-specification
//
// Manual updates to this file will be lost when the code is
// re-generated.
//
// If you find a property that is missing or wrongly typed, please
// open an issue or a PR on the API specification repository.
//
//----------------------------------------------------------------

// typedef: inference._types.ChatCompletionToolCall

/**
 * A tool call generated by the model.
 * 
 * @see <a href=
 *      "../doc-files/api-spec.html#inference._types.ChatCompletionToolCall">API
 *      specification</a>
 */
@JsonpDeserializable
public class ChatCompletionToolCall implements JsonpSerializable {
	private final int index;

	@Nullable
	private final String id;

	@Nullable
	private final ChatCompletionToolCallFunction function;

	private final String type;

	// ---------------------------------------------------------------------------------------------

	private ChatCompletionToolCall(Builder builder) {

		this.index = ApiTypeHelper.requireNonNull(builder.index, this, "index", 0);
		this.id = builder.id;
		this.function = builder.function;
		this.type = ApiTypeHelper.requireNonNull(builder.type, this, "type");

	}

	public static ChatCompletionToolCall of(Function<Builder, ObjectBuilder<ChatCompletionToolCall>> fn) {
		return fn.apply(new Builder()).build();
	}

	/**
	 * Required - The index of the tool call in the list of tool calls generated by
	 * the model.
	 * <p>
	 * API name: {@code index}
	 */
	public final int index() {
		return this.index;
	}

	/**
	 * The identifier of the tool call.
	 * <p>
	 * API name: {@code id}
	 */
	@Nullable
	public final String id() {
		return this.id;
	}

	/**
	 * The function that the model called.
	 * <p>
	 * API name: {@code function}
	 */
	@Nullable
	public final ChatCompletionToolCallFunction function() {
		return this.function;
	}

	/**
	 * Required - The type of the tool call.
	 * <p>
	 * API name: {@code type}
	 */
	public final String type() {
		return this.type;
	}

	/**
	 * Serialize this object to JSON.
	 */
	public void serialize(JsonGenerator generator, JsonpMapper mapper) {
		generator.writeStartObject();
		serializeInternal(generator, mapper);
		generator.writeEnd();
	}

	protected void serializeInternal(JsonGenerator generator, JsonpMapper mapper) {

		generator.writeKey("index");
		generator.write(this.index);

		if (this.id != null) {
			generator.writeKey("id");
			generator.write(this.id);

		}
		if (this.function != null) {
			generator.writeKey("function");
			this.function.serialize(generator, mapper);

		}
		generator.writeKey("type");
		generator.write(this.type);

	}

	@Override
	public String toString() {
		return JsonpUtils.toString(this);
	}

	// ---------------------------------------------------------------------------------------------

	/**
	 * Builder for {@link ChatCompletionToolCall}.
	 */

	public static class Builder extends WithJsonObjectBuilderBase<Builder>
			implements
				ObjectBuilder<ChatCompletionToolCall> {
		private Integer index;

		@Nullable
		private String id;

		@Nullable
		private ChatCompletionToolCallFunction function;

		private String type;

		public Builder() {
		}
		private Builder(ChatCompletionToolCall instance) {
			this.index = instance.index;
			this.id = instance.id;
			this.function = instance.function;
			this.type = instance.type;

		}
		/**
		 * Required - The index of the tool call in the list of tool calls generated by
		 * the model.
		 * <p>
		 * API name: {@code index}
		 */
		public final Builder index(int value) {
			this.index = value;
			return this;
		}

		/**
		 * The identifier of the tool call.
		 * <p>
		 * API name: {@code id}
		 */
		public final Builder id(@Nullable String value) {
			this.id = value;
			return this;
		}

		/**
		 * The function that the model called.
		 * <p>
		 * API name: {@code function}
		 */
		public final Builder function(@Nullable ChatCompletionToolCallFunction value) {
			this.function = value;
			return this;
		}

		/**
		 * The function that the model called.
		 * <p>
		 * API name: {@code function}
		 */
		public final Builder function(
				Function<ChatCompletionToolCallFunction.Builder, ObjectBuilder<ChatCompletionToolCallFunction>> fn) {
			return this.function(fn.apply(new ChatCompletionToolCallFunction.Builder()).build());
		}

		/**
		 * Required - The type of the tool call.
		 * <p>
		 * API name: {@code type}
		 */
		public final Builder type(String value) {
			this.type = value;
			return this;
		}

		@Override
		protected Builder self() {
			return this;
		}

		/**
		 * Builds a {@link ChatCompletionToolCall}.
		 *
		 * @throws NullPointerException
		 *             if some of the required fields are null.
		 */
		public ChatCompletionToolCall build() {
			_checkSingleUse();

			return new ChatCompletionToolCall(this);
		}
	}

	/**
	 * @return New {@link Builder} initialized with field values of this instance
	 */
	public Builder rebuild() {
		return new Builder(this);
	}
	// ---------------------------------------------------------------------------------------------

	/**
	 * Json deserializer for {@link ChatCompletionToolCall}
	 */
	public static final JsonpDeserializer<ChatCompletionToolCall> _DESERIALIZER = ObjectBuilderDeserializer
			.lazy(Builder::new, ChatCompletionToolCall::setupChatCompletionToolCallDeserializer);

	protected static void setupChatCompletionToolCallDeserializer(
			ObjectDeserializer<ChatCompletionToolCall.Builder> op) {

		op.add(Builder::index, JsonpDeserializer.integerDeserializer(), "index");
		op.add(Builder::id, JsonpDeserializer.stringDeserializer(), "id");
		op.add(Builder::function, ChatCompletionToolCallFunction._DESERIALIZER, "function");
		op.add(Builder::type, JsonpDeserializer.stringDeserializer(), "type");

	}

}
