/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package co.elastic.clients.elasticsearch.inference;

import co.elastic.clients.json.JsonpDeserializable;
import co.elastic.clients.json.JsonpDeserializer;
import co.elastic.clients.json.JsonpMapper;
import co.elastic.clients.json.JsonpSerializable;
import co.elastic.clients.json.JsonpUtils;
import co.elastic.clients.json.ObjectBuilderDeserializer;
import co.elastic.clients.json.ObjectDeserializer;
import co.elastic.clients.util.ApiTypeHelper;
import co.elastic.clients.util.ObjectBuilder;
import co.elastic.clients.util.WithJsonObjectBuilderBase;
import jakarta.json.stream.JsonGenerator;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.function.Function;
import javax.annotation.Nullable;

//----------------------------------------------------------------
//       THIS CODE IS GENERATED. MANUAL EDITS WILL BE LOST.
//----------------------------------------------------------------
//
// This code is generated from the Elasticsearch API specification
// at https://github.com/elastic/elasticsearch-specification
//
// Manual updates to this file will be lost when the code is
// re-generated.
//
// If you find a property that is missing or wrongly typed, please
// open an issue or a PR on the API specification repository.
//
//----------------------------------------------------------------

// typedef: inference._types.ChatCompletionChoice

/**
 * A single completion choice returned by the model.
 * 
 * @see <a href=
 *      "../doc-files/api-spec.html#inference._types.ChatCompletionChoice">API
 *      specification</a>
 */
@JsonpDeserializable
public class ChatCompletionChoice implements JsonpSerializable {
	private final ChatCompletionMessage message;

	@Nullable
	private final String finishReason;

	private final int index;

	// ---------------------------------------------------------------------------------------------

	private ChatCompletionChoice(Builder builder) {

		this.message = ApiTypeHelper.requireNonNull(builder.message, this, "message");
		this.finishReason = builder.finishReason;
		this.index = ApiTypeHelper.requireNonNull(builder.index, this, "index", 0);

	}

	public static ChatCompletionChoice of(Function<Builder, ObjectBuilder<ChatCompletionChoice>> fn) {
		return fn.apply(new Builder()).build();
	}

	/**
	 * Required - The message generated by the model for this choice.
	 * <p>
	 * API name: {@code message}
	 */
	public final ChatCompletionMessage message() {
		return this.message;
	}

	/**
	 * The reason the model stopped generating tokens. Common values are
	 * <code>stop</code> (natural stopping point) and <code>tool_calls</code> (the
	 * model called a tool). Omitted when the reason is not available.
	 * <p>
	 * API name: {@code finish_reason}
	 */
	@Nullable
	public final String finishReason() {
		return this.finishReason;
	}

	/**
	 * Required - The index of this choice in the list of choices.
	 * <p>
	 * API name: {@code index}
	 */
	public final int index() {
		return this.index;
	}

	/**
	 * Serialize this object to JSON.
	 */
	public void serialize(JsonGenerator generator, JsonpMapper mapper) {
		generator.writeStartObject();
		serializeInternal(generator, mapper);
		generator.writeEnd();
	}

	protected void serializeInternal(JsonGenerator generator, JsonpMapper mapper) {

		generator.writeKey("message");
		this.message.serialize(generator, mapper);

		if (this.finishReason != null) {
			generator.writeKey("finish_reason");
			generator.write(this.finishReason);

		}
		generator.writeKey("index");
		generator.write(this.index);

	}

	@Override
	public String toString() {
		return JsonpUtils.toString(this);
	}

	// ---------------------------------------------------------------------------------------------

	/**
	 * Builder for {@link ChatCompletionChoice}.
	 */

	public static class Builder extends WithJsonObjectBuilderBase<Builder>
			implements
				ObjectBuilder<ChatCompletionChoice> {
		private ChatCompletionMessage message;

		@Nullable
		private String finishReason;

		private Integer index;

		public Builder() {
		}
		private Builder(ChatCompletionChoice instance) {
			this.message = instance.message;
			this.finishReason = instance.finishReason;
			this.index = instance.index;

		}
		/**
		 * Required - The message generated by the model for this choice.
		 * <p>
		 * API name: {@code message}
		 */
		public final Builder message(ChatCompletionMessage value) {
			this.message = value;
			return this;
		}

		/**
		 * Required - The message generated by the model for this choice.
		 * <p>
		 * API name: {@code message}
		 */
		public final Builder message(Function<ChatCompletionMessage.Builder, ObjectBuilder<ChatCompletionMessage>> fn) {
			return this.message(fn.apply(new ChatCompletionMessage.Builder()).build());
		}

		/**
		 * The reason the model stopped generating tokens. Common values are
		 * <code>stop</code> (natural stopping point) and <code>tool_calls</code> (the
		 * model called a tool). Omitted when the reason is not available.
		 * <p>
		 * API name: {@code finish_reason}
		 */
		public final Builder finishReason(@Nullable String value) {
			this.finishReason = value;
			return this;
		}

		/**
		 * Required - The index of this choice in the list of choices.
		 * <p>
		 * API name: {@code index}
		 */
		public final Builder index(int value) {
			this.index = value;
			return this;
		}

		@Override
		protected Builder self() {
			return this;
		}

		/**
		 * Builds a {@link ChatCompletionChoice}.
		 *
		 * @throws NullPointerException
		 *             if some of the required fields are null.
		 */
		public ChatCompletionChoice build() {
			_checkSingleUse();

			return new ChatCompletionChoice(this);
		}
	}

	/**
	 * @return New {@link Builder} initialized with field values of this instance
	 */
	public Builder rebuild() {
		return new Builder(this);
	}
	// ---------------------------------------------------------------------------------------------

	/**
	 * Json deserializer for {@link ChatCompletionChoice}
	 */
	public static final JsonpDeserializer<ChatCompletionChoice> _DESERIALIZER = ObjectBuilderDeserializer
			.lazy(Builder::new, ChatCompletionChoice::setupChatCompletionChoiceDeserializer);

	protected static void setupChatCompletionChoiceDeserializer(ObjectDeserializer<ChatCompletionChoice.Builder> op) {

		op.add(Builder::message, ChatCompletionMessage._DESERIALIZER, "message");
		op.add(Builder::finishReason, JsonpDeserializer.stringDeserializer(), "finish_reason");
		op.add(Builder::index, JsonpDeserializer.integerDeserializer(), "index");

	}

}
