/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package co.elastic.clients.elasticsearch.inference;

import co.elastic.clients.json.JsonpDeserializable;
import co.elastic.clients.json.JsonpDeserializer;
import co.elastic.clients.json.JsonpMapper;
import co.elastic.clients.json.JsonpSerializable;
import co.elastic.clients.json.JsonpUtils;
import co.elastic.clients.json.ObjectBuilderDeserializer;
import co.elastic.clients.json.ObjectDeserializer;
import co.elastic.clients.util.ApiTypeHelper;
import co.elastic.clients.util.ObjectBuilder;
import co.elastic.clients.util.WithJsonObjectBuilderBase;
import jakarta.json.stream.JsonGenerator;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.function.Function;
import javax.annotation.Nullable;

//----------------------------------------------------------------
//       THIS CODE IS GENERATED. MANUAL EDITS WILL BE LOST.
//----------------------------------------------------------------
//
// This code is generated from the Elasticsearch API specification
// at https://github.com/elastic/elasticsearch-specification
//
// Manual updates to this file will be lost when the code is
// re-generated.
//
// If you find a property that is missing or wrongly typed, please
// open an issue or a PR on the API specification repository.
//
//----------------------------------------------------------------

// typedef: inference._types.ChatCompletionMessage

/**
 * The message returned by the model.
 * 
 * @see <a href=
 *      "../doc-files/api-spec.html#inference._types.ChatCompletionMessage">API
 *      specification</a>
 */
@JsonpDeserializable
public class ChatCompletionMessage implements JsonpSerializable {
	@Nullable
	private final String content;

	@Nullable
	private final String refusal;

	@Nullable
	private final String role;

	@Nullable
	private final String reasoning;

	private final List<ChatCompletionToolCall> toolCalls;

	private final List<ReasoningDetail> reasoningDetails;

	// ---------------------------------------------------------------------------------------------

	private ChatCompletionMessage(Builder builder) {

		this.content = builder.content;
		this.refusal = builder.refusal;
		this.role = builder.role;
		this.reasoning = builder.reasoning;
		this.toolCalls = ApiTypeHelper.unmodifiable(builder.toolCalls);
		this.reasoningDetails = ApiTypeHelper.unmodifiable(builder.reasoningDetails);

	}

	public static ChatCompletionMessage of(Function<Builder, ObjectBuilder<ChatCompletionMessage>> fn) {
		return fn.apply(new Builder()).build();
	}

	/**
	 * The content of the message.
	 * <p>
	 * API name: {@code content}
	 */
	@Nullable
	public final String content() {
		return this.content;
	}

	/**
	 * The refusal message generated by the model.
	 * <p>
	 * API name: {@code refusal}
	 */
	@Nullable
	public final String refusal() {
		return this.refusal;
	}

	/**
	 * The role of the message author.
	 * <p>
	 * API name: {@code role}
	 */
	@Nullable
	public final String role() {
		return this.role;
	}

	/**
	 * The reasoning generated by the model as plaintext. Currently supported only
	 * for the <code>elastic</code> provider.
	 * <p>
	 * API name: {@code reasoning}
	 */
	@Nullable
	public final String reasoning() {
		return this.reasoning;
	}

	/**
	 * The tool calls generated by the model.
	 * <p>
	 * API name: {@code tool_calls}
	 */
	public final List<ChatCompletionToolCall> toolCalls() {
		return this.toolCalls;
	}

	/**
	 * The reasoning details generated by the model as structured data. Currently
	 * supported only for the <code>elastic</code> provider.
	 * <p>
	 * API name: {@code reasoning_details}
	 */
	public final List<ReasoningDetail> reasoningDetails() {
		return this.reasoningDetails;
	}

	/**
	 * Serialize this object to JSON.
	 */
	public void serialize(JsonGenerator generator, JsonpMapper mapper) {
		generator.writeStartObject();
		serializeInternal(generator, mapper);
		generator.writeEnd();
	}

	protected void serializeInternal(JsonGenerator generator, JsonpMapper mapper) {

		if (this.content != null) {
			generator.writeKey("content");
			generator.write(this.content);

		}
		if (this.refusal != null) {
			generator.writeKey("refusal");
			generator.write(this.refusal);

		}
		if (this.role != null) {
			generator.writeKey("role");
			generator.write(this.role);

		}
		if (this.reasoning != null) {
			generator.writeKey("reasoning");
			generator.write(this.reasoning);

		}
		if (ApiTypeHelper.isDefined(this.toolCalls)) {
			generator.writeKey("tool_calls");
			generator.writeStartArray();
			for (ChatCompletionToolCall item0 : this.toolCalls) {
				item0.serialize(generator, mapper);

			}
			generator.writeEnd();

		}
		if (ApiTypeHelper.isDefined(this.reasoningDetails)) {
			generator.writeKey("reasoning_details");
			generator.writeStartArray();
			for (ReasoningDetail item0 : this.reasoningDetails) {
				item0.serialize(generator, mapper);

			}
			generator.writeEnd();

		}

	}

	@Override
	public String toString() {
		return JsonpUtils.toString(this);
	}

	// ---------------------------------------------------------------------------------------------

	/**
	 * Builder for {@link ChatCompletionMessage}.
	 */

	public static class Builder extends WithJsonObjectBuilderBase<Builder>
			implements
				ObjectBuilder<ChatCompletionMessage> {
		@Nullable
		private String content;

		@Nullable
		private String refusal;

		@Nullable
		private String role;

		@Nullable
		private String reasoning;

		@Nullable
		private List<ChatCompletionToolCall> toolCalls;

		@Nullable
		private List<ReasoningDetail> reasoningDetails;

		public Builder() {
		}
		private Builder(ChatCompletionMessage instance) {
			this.content = instance.content;
			this.refusal = instance.refusal;
			this.role = instance.role;
			this.reasoning = instance.reasoning;
			this.toolCalls = instance.toolCalls;
			this.reasoningDetails = instance.reasoningDetails;

		}
		/**
		 * The content of the message.
		 * <p>
		 * API name: {@code content}
		 */
		public final Builder content(@Nullable String value) {
			this.content = value;
			return this;
		}

		/**
		 * The refusal message generated by the model.
		 * <p>
		 * API name: {@code refusal}
		 */
		public final Builder refusal(@Nullable String value) {
			this.refusal = value;
			return this;
		}

		/**
		 * The role of the message author.
		 * <p>
		 * API name: {@code role}
		 */
		public final Builder role(@Nullable String value) {
			this.role = value;
			return this;
		}

		/**
		 * The reasoning generated by the model as plaintext. Currently supported only
		 * for the <code>elastic</code> provider.
		 * <p>
		 * API name: {@code reasoning}
		 */
		public final Builder reasoning(@Nullable String value) {
			this.reasoning = value;
			return this;
		}

		/**
		 * The tool calls generated by the model.
		 * <p>
		 * API name: {@code tool_calls}
		 * <p>
		 * Adds all elements of <code>list</code> to <code>toolCalls</code>.
		 */
		public final Builder toolCalls(List<ChatCompletionToolCall> list) {
			this.toolCalls = _listAddAll(this.toolCalls, list);
			return this;
		}

		/**
		 * The tool calls generated by the model.
		 * <p>
		 * API name: {@code tool_calls}
		 * <p>
		 * Adds one or more values to <code>toolCalls</code>.
		 */
		public final Builder toolCalls(ChatCompletionToolCall value, ChatCompletionToolCall... values) {
			this.toolCalls = _listAdd(this.toolCalls, value, values);
			return this;
		}

		/**
		 * The tool calls generated by the model.
		 * <p>
		 * API name: {@code tool_calls}
		 * <p>
		 * Adds a value to <code>toolCalls</code> using a builder lambda.
		 */
		public final Builder toolCalls(
				Function<ChatCompletionToolCall.Builder, ObjectBuilder<ChatCompletionToolCall>> fn) {
			return toolCalls(fn.apply(new ChatCompletionToolCall.Builder()).build());
		}

		/**
		 * The reasoning details generated by the model as structured data. Currently
		 * supported only for the <code>elastic</code> provider.
		 * <p>
		 * API name: {@code reasoning_details}
		 * <p>
		 * Adds all elements of <code>list</code> to <code>reasoningDetails</code>.
		 */
		public final Builder reasoningDetails(List<ReasoningDetail> list) {
			this.reasoningDetails = _listAddAll(this.reasoningDetails, list);
			return this;
		}

		/**
		 * The reasoning details generated by the model as structured data. Currently
		 * supported only for the <code>elastic</code> provider.
		 * <p>
		 * API name: {@code reasoning_details}
		 * <p>
		 * Adds one or more values to <code>reasoningDetails</code>.
		 */
		public final Builder reasoningDetails(ReasoningDetail value, ReasoningDetail... values) {
			this.reasoningDetails = _listAdd(this.reasoningDetails, value, values);
			return this;
		}

		/**
		 * The reasoning details generated by the model as structured data. Currently
		 * supported only for the <code>elastic</code> provider.
		 * <p>
		 * API name: {@code reasoning_details}
		 * <p>
		 * Adds a value to <code>reasoningDetails</code> using a builder lambda.
		 */
		public final Builder reasoningDetails(Function<ReasoningDetail.Builder, ObjectBuilder<ReasoningDetail>> fn) {
			return reasoningDetails(fn.apply(new ReasoningDetail.Builder()).build());
		}

		@Override
		protected Builder self() {
			return this;
		}

		/**
		 * Builds a {@link ChatCompletionMessage}.
		 *
		 * @throws NullPointerException
		 *             if some of the required fields are null.
		 */
		public ChatCompletionMessage build() {
			_checkSingleUse();

			return new ChatCompletionMessage(this);
		}
	}

	/**
	 * @return New {@link Builder} initialized with field values of this instance
	 */
	public Builder rebuild() {
		return new Builder(this);
	}
	// ---------------------------------------------------------------------------------------------

	/**
	 * Json deserializer for {@link ChatCompletionMessage}
	 */
	public static final JsonpDeserializer<ChatCompletionMessage> _DESERIALIZER = ObjectBuilderDeserializer
			.lazy(Builder::new, ChatCompletionMessage::setupChatCompletionMessageDeserializer);

	protected static void setupChatCompletionMessageDeserializer(ObjectDeserializer<ChatCompletionMessage.Builder> op) {

		op.add(Builder::content, JsonpDeserializer.stringDeserializer(), "content");
		op.add(Builder::refusal, JsonpDeserializer.stringDeserializer(), "refusal");
		op.add(Builder::role, JsonpDeserializer.stringDeserializer(), "role");
		op.add(Builder::reasoning, JsonpDeserializer.stringDeserializer(), "reasoning");
		op.add(Builder::toolCalls, JsonpDeserializer.arrayDeserializer(ChatCompletionToolCall._DESERIALIZER),
				"tool_calls");
		op.add(Builder::reasoningDetails, JsonpDeserializer.arrayDeserializer(ReasoningDetail._DESERIALIZER),
				"reasoning_details");

	}

}
