/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package co.elastic.clients.elasticsearch.inference;

import co.elastic.clients.json.JsonpDeserializable;
import co.elastic.clients.json.JsonpDeserializer;
import co.elastic.clients.json.JsonpMapper;
import co.elastic.clients.json.ObjectBuilderDeserializer;
import co.elastic.clients.json.ObjectDeserializer;
import co.elastic.clients.util.ApiTypeHelper;
import co.elastic.clients.util.ObjectBuilder;
import jakarta.json.stream.JsonGenerator;
import java.lang.String;
import java.util.Objects;
import java.util.function.Function;
import javax.annotation.Nullable;

//----------------------------------------------------------------
//       THIS CODE IS GENERATED. MANUAL EDITS WILL BE LOST.
//----------------------------------------------------------------
//
// This code is generated from the Elasticsearch API specification
// at https://github.com/elastic/elasticsearch-specification
//
// Manual updates to this file will be lost when the code is
// re-generated.
//
// If you find a property that is missing or wrongly typed, please
// open an issue or a PR on the API specification repository.
//
//----------------------------------------------------------------

// typedef: inference._types.EncryptedReasoningDetail

/**
 * The reasoning detail with encrypted reasoning data that may be redacted or
 * protected.
 * 
 * @see <a href=
 *      "../doc-files/api-spec.html#inference._types.EncryptedReasoningDetail">API
 *      specification</a>
 */
@JsonpDeserializable
public class EncryptedReasoningDetail extends BaseReasoningDetail implements ReasoningDetailVariant {
	private final String data;

	// ---------------------------------------------------------------------------------------------

	private EncryptedReasoningDetail(Builder builder) {
		super(builder);

		this.data = ApiTypeHelper.requireNonNull(builder.data, this, "data");

	}

	public static EncryptedReasoningDetail of(Function<Builder, ObjectBuilder<EncryptedReasoningDetail>> fn) {
		return fn.apply(new Builder()).build();
	}

	/**
	 * ReasoningDetail variant kind.
	 */
	@Override
	public ReasoningDetail.Kind _reasoningDetailKind() {
		return ReasoningDetail.Kind.ReasoningEncrypted;
	}

	/**
	 * Required - The encrypted reasoning data generated by the model, which may be
	 * redacted or protected based on the model's configuration and the nature of
	 * the reasoning information.
	 * <p>
	 * API name: {@code data}
	 */
	public final String data() {
		return this.data;
	}

	protected void serializeInternal(JsonGenerator generator, JsonpMapper mapper) {

		generator.write("type", "reasoning.encrypted");
		super.serializeInternal(generator, mapper);
		generator.writeKey("data");
		generator.write(this.data);

	}

	// ---------------------------------------------------------------------------------------------

	/**
	 * Builder for {@link EncryptedReasoningDetail}.
	 */

	public static class Builder extends BaseReasoningDetail.AbstractBuilder<Builder>
			implements
				ObjectBuilder<EncryptedReasoningDetail> {
		private String data;

		public Builder() {
		}
		private Builder(EncryptedReasoningDetail instance) {
			this.data = instance.data;

		}
		/**
		 * Required - The encrypted reasoning data generated by the model, which may be
		 * redacted or protected based on the model's configuration and the nature of
		 * the reasoning information.
		 * <p>
		 * API name: {@code data}
		 */
		public final Builder data(String value) {
			this.data = value;
			return this;
		}

		@Override
		protected Builder self() {
			return this;
		}

		/**
		 * Builds a {@link EncryptedReasoningDetail}.
		 *
		 * @throws NullPointerException
		 *             if some of the required fields are null.
		 */
		public EncryptedReasoningDetail build() {
			_checkSingleUse();

			return new EncryptedReasoningDetail(this);
		}
	}

	/**
	 * @return New {@link Builder} initialized with field values of this instance
	 */
	public Builder rebuild() {
		return new Builder(this);
	}
	// ---------------------------------------------------------------------------------------------

	/**
	 * Json deserializer for {@link EncryptedReasoningDetail}
	 */
	public static final JsonpDeserializer<EncryptedReasoningDetail> _DESERIALIZER = ObjectBuilderDeserializer
			.lazy(Builder::new, EncryptedReasoningDetail::setupEncryptedReasoningDetailDeserializer);

	protected static void setupEncryptedReasoningDetailDeserializer(
			ObjectDeserializer<EncryptedReasoningDetail.Builder> op) {
		BaseReasoningDetail.setupBaseReasoningDetailDeserializer(op);
		op.add(Builder::data, JsonpDeserializer.stringDeserializer(), "data");

		op.ignore("type");
	}

}
