/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package co.elastic.clients.elasticsearch.inference;

import co.elastic.clients.json.JsonpDeserializable;
import co.elastic.clients.json.JsonpDeserializer;
import co.elastic.clients.json.JsonpMapper;
import co.elastic.clients.json.ObjectBuilderDeserializer;
import co.elastic.clients.json.ObjectDeserializer;
import co.elastic.clients.util.ApiTypeHelper;
import co.elastic.clients.util.ObjectBuilder;
import jakarta.json.stream.JsonGenerator;
import java.lang.String;
import java.util.Objects;
import java.util.function.Function;
import javax.annotation.Nullable;

//----------------------------------------------------------------
//       THIS CODE IS GENERATED. MANUAL EDITS WILL BE LOST.
//----------------------------------------------------------------
//
// This code is generated from the Elasticsearch API specification
// at https://github.com/elastic/elasticsearch-specification
//
// Manual updates to this file will be lost when the code is
// re-generated.
//
// If you find a property that is missing or wrongly typed, please
// open an issue or a PR on the API specification repository.
//
//----------------------------------------------------------------

// typedef: inference._types.SummaryReasoningDetail

/**
 * The reasoning summary detail includes a high-level summary of the model's
 * reasoning process.
 * 
 * @see <a href=
 *      "../doc-files/api-spec.html#inference._types.SummaryReasoningDetail">API
 *      specification</a>
 */
@JsonpDeserializable
public class SummaryReasoningDetail extends BaseReasoningDetail implements ReasoningDetailVariant {
	private final String summary;

	// ---------------------------------------------------------------------------------------------

	private SummaryReasoningDetail(Builder builder) {
		super(builder);

		this.summary = ApiTypeHelper.requireNonNull(builder.summary, this, "summary");

	}

	public static SummaryReasoningDetail of(Function<Builder, ObjectBuilder<SummaryReasoningDetail>> fn) {
		return fn.apply(new Builder()).build();
	}

	/**
	 * ReasoningDetail variant kind.
	 */
	@Override
	public ReasoningDetail.Kind _reasoningDetailKind() {
		return ReasoningDetail.Kind.ReasoningSummary;
	}

	/**
	 * Required - The summary of the reasoning process generated by the model, which
	 * provides an overview of the key points and conclusions reached during the
	 * reasoning process.
	 * <p>
	 * API name: {@code summary}
	 */
	public final String summary() {
		return this.summary;
	}

	protected void serializeInternal(JsonGenerator generator, JsonpMapper mapper) {

		generator.write("type", "reasoning.summary");
		super.serializeInternal(generator, mapper);
		generator.writeKey("summary");
		generator.write(this.summary);

	}

	// ---------------------------------------------------------------------------------------------

	/**
	 * Builder for {@link SummaryReasoningDetail}.
	 */

	public static class Builder extends BaseReasoningDetail.AbstractBuilder<Builder>
			implements
				ObjectBuilder<SummaryReasoningDetail> {
		private String summary;

		public Builder() {
		}
		private Builder(SummaryReasoningDetail instance) {
			this.summary = instance.summary;

		}
		/**
		 * Required - The summary of the reasoning process generated by the model, which
		 * provides an overview of the key points and conclusions reached during the
		 * reasoning process.
		 * <p>
		 * API name: {@code summary}
		 */
		public final Builder summary(String value) {
			this.summary = value;
			return this;
		}

		@Override
		protected Builder self() {
			return this;
		}

		/**
		 * Builds a {@link SummaryReasoningDetail}.
		 *
		 * @throws NullPointerException
		 *             if some of the required fields are null.
		 */
		public SummaryReasoningDetail build() {
			_checkSingleUse();

			return new SummaryReasoningDetail(this);
		}
	}

	/**
	 * @return New {@link Builder} initialized with field values of this instance
	 */
	public Builder rebuild() {
		return new Builder(this);
	}
	// ---------------------------------------------------------------------------------------------

	/**
	 * Json deserializer for {@link SummaryReasoningDetail}
	 */
	public static final JsonpDeserializer<SummaryReasoningDetail> _DESERIALIZER = ObjectBuilderDeserializer
			.lazy(Builder::new, SummaryReasoningDetail::setupSummaryReasoningDetailDeserializer);

	protected static void setupSummaryReasoningDetailDeserializer(
			ObjectDeserializer<SummaryReasoningDetail.Builder> op) {
		BaseReasoningDetail.setupBaseReasoningDetailDeserializer(op);
		op.add(Builder::summary, JsonpDeserializer.stringDeserializer(), "summary");

		op.ignore("type");
	}

}
