/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package co.elastic.clients.elasticsearch.inference;

import co.elastic.clients.json.JsonpDeserializable;
import co.elastic.clients.json.JsonpDeserializer;
import co.elastic.clients.json.JsonpMapper;
import co.elastic.clients.json.ObjectBuilderDeserializer;
import co.elastic.clients.json.ObjectDeserializer;
import co.elastic.clients.util.ObjectBuilder;
import jakarta.json.stream.JsonGenerator;
import java.lang.String;
import java.util.Objects;
import java.util.function.Function;
import javax.annotation.Nullable;

//----------------------------------------------------------------
//       THIS CODE IS GENERATED. MANUAL EDITS WILL BE LOST.
//----------------------------------------------------------------
//
// This code is generated from the Elasticsearch API specification
// at https://github.com/elastic/elasticsearch-specification
//
// Manual updates to this file will be lost when the code is
// re-generated.
//
// If you find a property that is missing or wrongly typed, please
// open an issue or a PR on the API specification repository.
//
//----------------------------------------------------------------

// typedef: inference._types.TextReasoningDetail

/**
 * The reasoning text detail includes plaintext reasoning with optional
 * signature verification.
 * 
 * @see <a href=
 *      "../doc-files/api-spec.html#inference._types.TextReasoningDetail">API
 *      specification</a>
 */
@JsonpDeserializable
public class TextReasoningDetail extends BaseReasoningDetail implements ReasoningDetailVariant {
	@Nullable
	private final String signature;

	@Nullable
	private final String text;

	// ---------------------------------------------------------------------------------------------

	private TextReasoningDetail(Builder builder) {
		super(builder);

		this.signature = builder.signature;
		this.text = builder.text;

	}

	public static TextReasoningDetail of(Function<Builder, ObjectBuilder<TextReasoningDetail>> fn) {
		return fn.apply(new Builder()).build();
	}

	/**
	 * ReasoningDetail variant kind.
	 */
	@Override
	public ReasoningDetail.Kind _reasoningDetailKind() {
		return ReasoningDetail.Kind.ReasoningText;
	}

	/**
	 * The signature of the reasoning text, which can be used to verify the
	 * authenticity and integrity of the reasoning information provided by the
	 * model.
	 * <p>
	 * API name: {@code signature}
	 */
	@Nullable
	public final String signature() {
		return this.signature;
	}

	/**
	 * The plaintext reasoning generated by the model, which provides a detailed
	 * explanation of the model's reasoning process in human-readable form.
	 * <p>
	 * API name: {@code text}
	 */
	@Nullable
	public final String text() {
		return this.text;
	}

	protected void serializeInternal(JsonGenerator generator, JsonpMapper mapper) {

		generator.write("type", "reasoning.text");
		super.serializeInternal(generator, mapper);
		if (this.signature != null) {
			generator.writeKey("signature");
			generator.write(this.signature);

		}
		if (this.text != null) {
			generator.writeKey("text");
			generator.write(this.text);

		}

	}

	// ---------------------------------------------------------------------------------------------

	/**
	 * Builder for {@link TextReasoningDetail}.
	 */

	public static class Builder extends BaseReasoningDetail.AbstractBuilder<Builder>
			implements
				ObjectBuilder<TextReasoningDetail> {
		@Nullable
		private String signature;

		@Nullable
		private String text;

		public Builder() {
		}
		private Builder(TextReasoningDetail instance) {
			this.signature = instance.signature;
			this.text = instance.text;

		}
		/**
		 * The signature of the reasoning text, which can be used to verify the
		 * authenticity and integrity of the reasoning information provided by the
		 * model.
		 * <p>
		 * API name: {@code signature}
		 */
		public final Builder signature(@Nullable String value) {
			this.signature = value;
			return this;
		}

		/**
		 * The plaintext reasoning generated by the model, which provides a detailed
		 * explanation of the model's reasoning process in human-readable form.
		 * <p>
		 * API name: {@code text}
		 */
		public final Builder text(@Nullable String value) {
			this.text = value;
			return this;
		}

		@Override
		protected Builder self() {
			return this;
		}

		/**
		 * Builds a {@link TextReasoningDetail}.
		 *
		 * @throws NullPointerException
		 *             if some of the required fields are null.
		 */
		public TextReasoningDetail build() {
			_checkSingleUse();

			return new TextReasoningDetail(this);
		}
	}

	/**
	 * @return New {@link Builder} initialized with field values of this instance
	 */
	public Builder rebuild() {
		return new Builder(this);
	}
	// ---------------------------------------------------------------------------------------------

	/**
	 * Json deserializer for {@link TextReasoningDetail}
	 */
	public static final JsonpDeserializer<TextReasoningDetail> _DESERIALIZER = ObjectBuilderDeserializer
			.lazy(Builder::new, TextReasoningDetail::setupTextReasoningDetailDeserializer);

	protected static void setupTextReasoningDetailDeserializer(ObjectDeserializer<TextReasoningDetail.Builder> op) {
		BaseReasoningDetail.setupBaseReasoningDetailDeserializer(op);
		op.add(Builder::signature, JsonpDeserializer.stringDeserializer(), "signature");
		op.add(Builder::text, JsonpDeserializer.stringDeserializer(), "text");

		op.ignore("type");
	}

}
