steps:
  - label: ":java: :elasticsearch: Elasticsearch Java API client - {{matrix.workflow}}"
    agents:
      provider: "gcp"
    branches: [ "main", "7.17", "8.15", "8.x", "9.0" ]
    matrix:
      setup:
        workflow:
          - "snapshot"
          - "staging"
    command: ".ci/release.sh {{matrix.workflow}}"
