steps:
  - label: ":java: :elasticsearch: Elasticsearch Java API client DRA - {{matrix.workflow}}"
    agents:
      provider: "gcp"
    branches: [ "main", "7.17", "8.17", "8.18", "8.x", "9.0" ]
    matrix:
      setup:
        workflow:
          - "snapshot"
          - "staging"
    command: ".ci/release_dra.sh {{matrix.workflow}}"
