name: Feature Request
description: Request a new feature
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Please first search existing issues for the feature you are requesting. It may already exist, even as a closed issue.
        If it exists, please add a comment: along with subscribing you to the issue, this will help us prioritize features.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give us as much context as possible about the feature.
