[[loading-json]]
=== Creating API objects from JSON data

ifeval::["{minor-version}" == "7.17"]
NOTE: This feature was added in version 7.17.2
endif::[]

ifeval::["{minor-version}" == "8.1"]
NOTE: This feature was added in version 8.1.1
endif::[]

A common workflow during application development with Elasticsearch is to use the Kibana Developer Console to interactively prepare and test queries, aggregations, index mappings and other complex API calls. This results in working JSON snippets that you may want to use in your application.

As translating these JSON snippets to Java code can be time-consuming and error-prone, most of the data classes in the {java-client} can be loaded from JSON text: object builders have `withJson()` methods that populate the builder from raw JSON. This also allows you to combine dynamically loaded JSON with programmatic construction of objects.

Under the hood, the `withJson()` methods call the object's deserializer. The JSON text's structure and value types therefore have to be correct for the target data structure. Using `withJson()` keeps the strong typing guarantees of the {java-client}.

[discrete]
==== Examples

[discrete]
===== Loading an index definition from a resource file

Consider a resource file `some-index.json` containing an index definition:

["source", "json"]
--------------------------------------------------
{
  "mappings": {
    "properties": {
      "field1": { "type": "text" }
    }
  }
}
--------------------------------------------------

You can create an index from that definition as follows:

["source","java"]
--------------------------------------------------
include-tagged::{doc-tests-src}/api_conventions/LoadingJsonTest.java[load-index]
--------------------------------------------------
<1> open an input stream for the JSON resource file.
<2> populate the index creation request with the resource file contents.

[discrete]
===== Ingesting documents from JSON files

Similarly, you can read documents to be stored in {es} from data files:

["source","java"]
--------------------------------------------------
include-tagged::{doc-tests-src}/api_conventions/LoadingJsonTest.java[ingest-data]
--------------------------------------------------
<1> when calling `withJson()` on data structures that have generic type parameters, these generic types will be considered to be `JsonData`.

[discrete]
===== Creating a search request combining JSON and programmatic construction

You can combine `withJson()` with regular calls to setter methods. The example below loads the query part of a search request from a `String` and programmatically adds an aggregation.

["source","java"]
--------------------------------------------------
include-tagged::{doc-tests-src}/api_conventions/LoadingJsonTest.java[query]
--------------------------------------------------
<1> loads the query from the JSON string.
<2> adds the aggregation.
<3> since this is an aggregation we don't care about result documents and set their target class to `Void`, meaning they will just be ignored. Note that setting `size` to zero actually prevents any document from being returned.

[discrete]
===== Creating a search request from multiple JSON snippets

The `withJson()` methods are partial deserializers: the properties loaded from the JSON will set property values or replace the previous ones, but will not reset other properties not found in the JSON input. You can use this to combine multiple JSON snippets to build complex search requests. In the example below, we combine separate definitions of a query that selects some documents and an aggregation that is run on the results of this query.

["source","java"]
--------------------------------------------------
include-tagged::{doc-tests-src}/api_conventions/LoadingJsonTest.java[query-and-agg]
--------------------------------------------------
<1> set max number of returned document to 100 for queries.
<2> we do not want any matching document in aggregations.
<3> loads the query part of the request.
<4> loads the aggregation part of the request (overwrites `size` from the query).
<5> additional request properties set programmatically.

Notice that order matters when the JSON snippets have some common properties: just as when setting property values programmatically, the last value that is set for a property overwrites the previous one.

{doc-tests-blurb}
