[[introduction]]
== Introduction

This is the documentation for the official Java API Client for {es}. The client 
provides strongly typed requests and responses for all {es} APIs.

[discrete]
=== Features

* Strongly typed requests and responses for all {es} APIs.
* Blocking and asynchronous versions of all APIs.
* Use of fluent builders and functional patterns to allow writing concise yet 
  readable code when creating complex nested structures.
* Seamless integration of application classes by using an object mapper such as 
  Jackson or any JSON-B implementation.
* Delegates protocol handling to an http client such as the <<java-rest-low>> 
  that takes care of all transport-level concerns: HTTP connection pooling, 
  retries, node discovery, and so on.

[discrete]
=== Elasticsearch server compatibility policy

The {es} Java client is forward compatible; meaning that the client supports 
communicating with greater or equal minor versions of {es}. {es} language 
clients are only backwards compatible with default distributions and without 
guarantees made.
