[[introduction]]
== Introduction

This is the documentation for the official Java API Client for {es}. The client 
provides strongly typed requests and responses for all {es} APIs.

[discrete]
=== Features

* Strongly typed requests and responses for all {es} APIs.
* Blocking and asynchronous versions of all APIs.
* Use of fluent builders and functional patterns to allow writing concise yet 
  readable code when creating complex nested structures.
* Seamless integration of application classes by using an object mapper such as 
  Jackson or any JSON-B implementation.
* Delegates protocol handling to an http client such as the <<java-rest-low>> 
  that takes care of all transport-level concerns: HTTP connection pooling, 
  retries, node discovery, and so on.

[discrete]
=== Main changes since version 7.15

Version 7.15 of the {java-client} was a beta release. We learned a lot from the
initial feedback and this led to a few breaking changes in this version:

* the `_core` package that contains top-level {es} APIs has been renamed to `core`.
* property setters for lists and maps have been revisited.
* all API data types are now supported, and there are no more raw `JsonValue` properties.
* the supporting JSON framework and transport classes have been refactored and improved.
  However the high level APIs used by applications haven't changed so there should be
  no or very little impact on existing application code.

This version of the {java-client} supports all {es} APIs are implemented except the
Vector tile search API and the Find structure API.

While this version is considered stable, most of the code is generated from the
https://github.com/elastic/elasticsearch-specification[{es} API specification] where
some of the less often used {es} APIs still need to be fully validated. Changes in
the specification that may impact application code will be clearly identified in later
versions of the Java API client.

[discrete]
=== Compatibility

The `main` branch targets the next major release (8.0), the `7.x` branch targets the
next minor release for the `7.x` series.

The {es} Java client is forward compatible; meaning that the client supports 
communicating with greater or equal minor versions of {es}. {es} language 
clients are only backwards compatible with default distributions and without 
guarantees made.
