[[reading]]
=== Reading documents by id

Elasticsearch is all about search, but you may also want to access documents directly, knowing their identifier. The "get" request is meant for this.

NOTE: See the {es-docs}/docs-get.html[{es} API documentation] for a full explanation of get requests.

[discrete]
==== Reading a domain object

The example below reads the document with identifier `bk-1` from the `products` index.

The `get` request has two parameters:

* the first parameter is the actual request, built below with the fluent DSL
* the second parameter is the class we want the document's JSON to be mapped to.

["source","java"]
--------------------------------------------------
include-tagged::{doc-tests-src}/usage/ReadingTest.java[get-by-id]
--------------------------------------------------
<1> The get request, with the index name and identifier.
<2> The target class, here `Product`.

[discrete]
==== Reading raw JSON

When your index contains semi-structured data or if you don't have a domain object definition, you can also read the document as raw JSON data.

Raw JSON data is just another class that you can use as the result type for the get request. In the example below we use Jackson's `ObjectNode`. We could also have used any JSON representation that can be deserialized by the JSON mapper associated to the `ElasticsearchClient`.

["source","java"]
--------------------------------------------------
include-tagged::{doc-tests-src}/usage/ReadingTest.java[get-by-id-json]
--------------------------------------------------
<1> The target class is a raw JSON object.

{doc-tests-blurb}


