name: Java Unit Tests

on:
  workflow_run:
    workflows: ['Validate Gradle Wrapper']
    types: [completed]
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set env
        run: echo "github_test=true" >> $GITHUB_ENV

      - name: Run java client tests
        run: ./gradlew test -p java-client
